title: Rami Saad
logo: assetsimage/profile_pic.jpg
description: Python/ SQL/ Tableau/ Excel/ Numpy/ Pandas/ Seaborn/ Matplotlib/ EDA/ APIs/ Web Scraping
#show_downloads: false
theme: jekyll-theme-minimal

