title: Rami Saad
logo: <img src="/assetsimage/profile_pic.jpg" width="600" height="350"/>
description: Python/ SQL/ Tableau/ Excel/ Numpy/ Pandas/ Seaborn/ Matplotlib/ EDA/ APIs/ Web Scraping
#show_downloads: false
theme: jekyll-theme-minimal
