title: Rami Saad
logo: assetsimage/WhatsApp Image 2024-07-19 at 16.24.50_cd21d00c.jpg
description: Python/ SQL/ Tableau/ Excel/ Numpy/ Pandas/ Seaborn/ Matplotlib/ EDA/ APIs/ Web Scraping
#show_downloads: false
theme: jekyll-theme-minimal

